### ISSUE TITLE
PFM support broken

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#353]
```
In file included from lo2s/src/perf/event_provider.cpp:27:
lo2s/include/lo2s/perf/pfm.hpp:25:10: fatal error: lo2s/perf/event_description.hpp: No such file or directory
   25 | #include <lo2s/perf/event_description.hpp>
      |       
```

Seems it was broken by c30368affbbaab019db60d844c8cae19b753f7bd

I suppose we'd like to have a PFM build in the CI.
